"""Prompt builder for a combined CV adaptation + motivation-letter call."""

from __future__ import annotations

from smartapply.llm.prompts.cv_adaptation import (
    _format_core_skills,
    _format_experiences,
    _format_matching_keywords,
    _format_projects,
    _format_skill_catalog,
    _format_unsupported_offer_terms,
)
from smartapply.llm.prompts.skill_profiles import format_skill_profiles
from smartapply.llm.schemas import JobAnalysis
from smartapply.profile import Experience, Profile, Project

SYSTEM = """You adapt a candidate's CV and write a motivation letter in one structured output.

Priority:
1. CV adaptation is the primary task.
2. The motivation letter is secondary and must combine safe offer anchors with selected CV/project evidence.
3. The email is NOT generated by the LLM; it is generated later by a deterministic template.
4. Do not introduce a new technical claim in the motivation letter if it is not supported by selected_experiences or selected_project_ids.
5. If CV and motivation letter optimization conflict, prioritize CV accuracy and relevance.

Internal generation order:
1. Identify the role family and strongest evidence.
2. Select relevant experiences, bullets, projects and skills first.
3. Adapt the CV conservatively using only allowed_claims.
4. Write the motivation letter from safe offer anchors plus selected CV/project evidence.
5. Output only the final JSON.

Hard rules:
1. Every CV bullet MUST reference a real source_id from the provided list.
2. Every CV claim MUST come from the bullet's allowed_claims list.
3. Respect each bullet's evidence_level; be conservative for inferred claims.
4. Do NOT invent skills outside allowed_skills.
5. Do NOT change quantified results, dates, company names or project names.
6. The CV is ALWAYS in English, even when the job offer is in French.
7. Density rule (very important): default to the source bullet's exact phrasing — it is already dense and intentional. Only paraphrase when you can naturally surface an offer keyword without adding fluff. If the rewrite would be longer, heavier, or less natural than the source, keep the source bullet verbatim. Surfacing keywords is OPTIONAL.
8. When you do rephrase, you may only recombine/paraphrase the provided allowed_claims.
9. CV bullets must be concise (<= 220 chars), clear and faithful to the source.
10. selected_experiences MUST include every provided source experience and every provided source bullet. Do not remove bullets to optimize relevance. If a bullet cannot be naturally adapted to the offer, keep the source text verbatim.
11. If a source bullet declares ``links``, keep each ``anchor`` token verbatim in your output bullet — the renderer wraps it as a hyperlink. Do not embed any markdown link or HTML tag yourself.
12. The cv_title MUST be adapted to this role and MUST contain at least one specific role anchor from the job title, role_type or main_tasks. Generic default titles are forbidden.
13. The professional_summary MUST be adapted to this role, cite at least one concrete offer anchor, fit in 2 lines maximum, and use only facts from the source profile.
14. Generic default summaries are forbidden. Do not reuse broad phrases such as "applied AI, NLP and multimodal learning" unless those exact areas are directly relevant to the offer.
15. Choose exactly one skills_profile_id from the provided skill profile choices. Use matching_keywords only to understand the role family; they are NOT display skills.
16. The motivation letter body must have exactly 3 paragraphs separated by blank lines, plain and human, with no bullet list.
17. Paragraph 1: interest in the role/company/context, using 1 or 2 visible offer anchors only. Never invent company facts.
18. Paragraph 2: profile-to-role fit with 2 or 3 proofs maximum from selected evidence. Do not rewrite the CV.
19. Paragraph 3: concrete contribution plus a sober invitation to exchange. Do not add a fourth closing paragraph.
20. The motivation letter must cite one concrete project, stack or experience from the profile.
21. The motivation letter must reuse evidence from selected_experiences or selected_project_ids.
22. The motivation letter must be written only in French or English with Latin-script characters. Never output Arabic, Armenian, Cyrillic, Hebrew, CJK or mixed-script words.
23. selected_skills is the exact Skills section to display. Build organized category blocks from allowed_skills_by_category only.
24. Skill selection strategy: include offer-required skills that exist in allowed_skills; add core/profile skills only when they strengthen the application for this offer; omit generic or unrelated skills even if the candidate has them.
25. Unsupported offer terms are a no-claim list: do not describe the candidate as having those skills in the summary, bullets, title, skills, motivation letter or warnings.
26. Do not place unsupported_offer_terms_not_to_claim in cv_title or professional_summary as role anchors. Use supported adjacent anchors only when they are listed in allowed_skills_by_category or source evidence.
27. Never mention a lack, gap, missing experience, limited knowledge, junior status, willingness to learn, or apologies. If something is unsupported, simply omit it and emphasize supported strengths.
28. The motivation letter may reference only selected_project_ids and selected_experiences. Do not name or hint at projects that are not selected.
29. selected_project_ids must contain 2 to 4 projects. Include at least 3 only when 3 genuinely relevant projects are available. Do not select a project only as filler.
30. For French letters, use normal French typography with accents and apostrophes: write "j'ai", "d'IA", "l'IA", "m'ont", "qu'il"; never ASCII-fold French into "j ai", "d IA", "qualite" or "generative".
31. Output ONLY the requested JSON. No prose, no commentary.

Good motivation-letter pattern:
- Opening: mention a concrete company/context or offer anchor when available.
- Middle: connect a role mission/responsibility to one selected experience and one selected project/stack.
- Close: short professional call to action.

Forbidden motivation-letter patterns:
- "Although / Bien que..."
- "I do not have / Je n'ai pas..."
- "I am aware / Je suis conscient..."
- "I recognize / Je reconnais..."
- "limited knowledge / connaissance limitée..."
- "ready to learn / prêt à apprendre..."
"""


def _format_offer_interest_anchors(analysis: JobAnalysis) -> str:
    lines: list[str] = []
    if analysis.company_context.strip():
        lines.append(f"Company/context: {analysis.company_context.strip()}")
    for point in analysis.offer_interest_points:
        point = " ".join((point or "").split())
        if point:
            lines.append(f"- {point}")
    if lines:
        return "\n".join(lines)
    return (
        "No reliable company/about-us anchor extracted. Use only the visible "
        "domain, missions, responsibilities and required skills; do not invent "
        "company facts."
    )


def build_user_prompt(
    *,
    profile: Profile,
    analysis: JobAnalysis,
    job_title: str,
    job_company: str,
    selected_experiences: list[Experience],
    selected_projects: list[Project],
    language: str = "fr",
) -> str:
    allowed = ", ".join(sorted(profile.skills.allowed_skills))
    style = profile.style_guide
    dont = "\n  - ".join(style.dont)
    do = "\n  - ".join(style.do)
    main_tasks_block = "\n".join(f"- {t}" for t in analysis.main_tasks)
    project_hint = ", ".join(p.name for p in selected_projects[:3])
    skill_profiles = format_skill_profiles(profile)
    skill_catalog = _format_skill_catalog(profile)
    core_skills = _format_core_skills(profile)
    matching_keywords = _format_matching_keywords(profile)
    unsupported_offer_terms = _format_unsupported_offer_terms(profile, analysis)
    offer_interest_anchors = _format_offer_interest_anchors(analysis)

    return f"""Produce a complete CV and motivation-letter draft for this role.

=== JOB ===
Title: {job_title}
Company: {job_company}
Role type: {analysis.role_type}
Seniority: {analysis.seniority}
Domain: {analysis.domain}
Offer/company anchors for letter:
{offer_interest_anchors}
Main tasks:
{main_tasks_block}
Required skills: {', '.join(analysis.required_skills)}
Keywords to surface: {', '.join(analysis.cv_keywords_to_include)}
Match reasons: {', '.join(analysis.match_reasons)}
Risks to avoid overclaiming: {', '.join(analysis.risks)}

=== PROFILE (source of truth — do NOT invent) ===
candidate_name: {profile.identity.full_name}
candidate_title: {profile.identity.title}
summary_source: {profile.identity.summary}
allowed_skills: {allowed}
allowed_skills_by_category:
{skill_catalog}
core_skills_by_category:
{core_skills}
skill_profile_choices:
{skill_profiles}
matching_keywords_for_profile_selection_not_display:
{matching_keywords}
unsupported_offer_terms_not_to_claim:
{unsupported_offer_terms}

experiences (use bullet `id` as source_id in selected_experiences):
{_format_experiences(selected_experiences)}

projects:
{_format_projects(selected_projects)}

=== MOTIVATION LETTER ===
Motivation letter language: {"French" if language == "fr" else "English"}
Project hints for the letter: {project_hint}
Subject: concise, mentions the role and the candidate name. For French, use "Candidature - ..." rather than "Application for ...".
Body: exactly 3 paragraphs separated by blank lines. French: 180-260 words, target 200-230. English: 160-230 words, target 180-210. Natural, professional, no buzzwords, no bullet list.
Use only French or English Latin script. No Arabic, Armenian, Cyrillic, Hebrew, CJK or mixed-script words.
For French, keep normal apostrophes and accents; do not remove apostrophes after j, d, l, m, n, s, t, qu, jusqu, lorsqu or puisqu.
Paragraph 1: interest in the role/company/context, using 1 or 2 visible offer anchors only.
Paragraph 2: fit between profile and role, with 2 or 3 selected proofs maximum.
Paragraph 3: concrete contribution plus a sober invitation to exchange. Do not add a fourth closing paragraph.
Together, these three paragraphs must answer: why this company/context, why this role, why this candidate.
Use one concrete offer/company anchor from "Offer/company anchors for letter" when available, but never invent company facts or use "leader dans son domaine" / "industry leader" unless the offer proves it.
If no reliable company/about-us anchor is available, do not invent one; ground the opening in the domain, mission, responsibilities or required skills instead.
Connect the offer anchor to one role mission/responsibility and one selected candidate proof.
Do not turn the letter into a CV summary; keep candidate evidence selective and directly tied to the role.
The motivation letter must reuse evidence from selected_experiences or selected_project_ids.
It must cite one concrete project, stack or experience from the profile.
Do not claim unsupported_offer_terms_not_to_claim as candidate skills.
Do not copy unsupported_offer_terms_not_to_claim into the CV title or summary just because they appear in the job title or missions.
Do not claim "production", "mise en production", "industrialisation" or "deployment" as candidate experience unless the selected source evidence explicitly supports that wording. Safer alternatives are "pipelines", "API", "structured code" or "usable models" when supported.
If a required term is unsupported, emphasize adjacent allowed skills and concrete evidence.
Never mention a gap, missing experience, limited knowledge, learning need, apology, or defensive caveat. Do not use "Bien que", "Je reconnais", "Je suis conscient", "je n'ai pas", "limited", "although", or "ready to learn".
Only name projects that appear in selected_project_ids. If you name a project in the letter, that exact project id MUST be present in selected_project_ids. Do not use a real project as generic filler when it is not directly relevant.
Do not include a sign-off, signature, "Cordialement", "Best regards", or the candidate name in the motivation_letter_body; the renderer adds the canonical signature.

=== STYLE ===
Tone: {style.tone}
Voice: {style.voice}
CV language: English only. Keep cv_title, professional_summary and CV bullets in English.
CV title: must be role-specific and contain a concrete anchor from the job title, role_type or main_tasks. Do not reuse a generic default title.
Professional summary: adapt it to the job, mention at least one concrete offer anchor, max {style.max_summary_lines} lines and max {style.max_summary_length} characters. Use only summary_source, experiences, projects and allowed_skills.
Experience output: include every provided experience and every bullet id exactly once. Rephrase only when faithful; otherwise keep the source bullet.
Do:
  - {do}
Don't:
  - {dont}

Return JSON conforming to ApplicationDraft:
- CV fields: cv_title, professional_summary, selected_experiences, selected_project_ids, skills_profile_id, selected_skills, skills_order, warnings.
- Motivation letter fields: motivation_letter_subject, motivation_letter_body.

Project output rule:
- selected_project_ids must contain 2 to 4 projects.
- Include at least 3 only when 3 genuinely relevant projects are available.
- Rank projects by direct relevance to the job tasks, required skills and keywords.
- Do not pick a project only as filler.

Skills output rule:
- Fill selected_skills as a list of blocks: {{"category_id": "...", "skills": ["..."]}}.
- category_id must be one of the ids in allowed_skills_by_category.
- skills must be exact skill names from the matching allowed_skills_by_category block.
- Include every required or strongly requested offer skill that exists in allowed_skills.
- Use core_skills_by_category as a baseline only inside categories that are relevant to the offer.
- Use matching_keywords_for_profile_selection_not_display only for reasoning about the right skill profile/category; do not copy those keywords into selected_skills unless the exact term is also listed in allowed_skills_by_category.
- Treat unsupported_offer_terms_not_to_claim as a no-claim list. Do not put those terms in cv_title, professional_summary, selected_skills, rewritten bullets, motivation_letter_subject or motivation_letter_body as candidate capabilities.
- Do not cap selected_skills by number, but do not pad the section. Every displayed skill must add value for this specific application.
"""
