"""Persistence layer — SQLAlchemy models, session and repository."""

from smartapply.database.models import (
    Application,
    AppSetting,
    Base,
    EmbeddingCache,
    GeneratedDocument,
    Job,
    JobAnalysis,
    JobEmbedding,
    JobScore,
    JobStatus,
    LLMCache,
    LLMUsage,
    ShortlistOrigin,
)
from smartapply.database.session import (
    auto_migrate,
    backfill_shortlisted_at,
    backfill_usage_job_external_ids,
    drop_db,
    get_engine,
    get_session_factory,
    init_db,
    reset_engine_cache,
    session_scope,
)

__all__ = [
    "Application",
    "AppSetting",
    "Base",
    "EmbeddingCache",
    "GeneratedDocument",
    "Job",
    "JobAnalysis",
    "JobEmbedding",
    "JobScore",
    "JobStatus",
    "LLMCache",
    "LLMUsage",
    "ShortlistOrigin",
    "auto_migrate",
    "backfill_shortlisted_at",
    "backfill_usage_job_external_ids",
    "drop_db",
    "get_engine",
    "get_session_factory",
    "init_db",
    "reset_engine_cache",
    "session_scope",
]
